package com.ai.inference;

import java.util.Map;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.ai.chat.prompt.PromptTemplate;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Service;

@Service
public class AiInferenceService {

    private final ChatClient chatClient;

    // Inject the prompt file from src/main/resources
    @Value("classpath:/prompts/resume_prompt.txt")
    private Resource resumePromptResource;

    public AiInferenceService(ChatClient.Builder chatClientBuilder) {
        // Use the builder to create the ChatClient, which automatically uses the Ollama configuration
        this.chatClient = chatClientBuilder.build();
    }

    /**
     * Sends the user's description to the DeepSeek model using a pre-defined prompt template.
     * The model is expected to return a raw JSON string of the generated resume data.
     *
     * @param userDescription The input text describing the user's background/goals.
     * @return The raw JSON string generated by the LLM.
     */
    public String generateResume(String userDescription) {
        // 1. Load the prompt template from the file
        PromptTemplate promptTemplate = new PromptTemplate(resumePromptResource);

        // 2. Create the prompt with the dynamic user input
        Prompt prompt = promptTemplate.create(Map.of("userDescription", userDescription));

        // 3. Call the AI model and get the content
        return chatClient.prompt(prompt).call().content();
    }
}